version: "3.9"
services:
  bentica:
    build: .
    ports:
      - "8080:8080"
    links:
      - monguito
  monguito:
    image: mongo
    ports:
      - "27017:27017"
    # environment:
    #   - MONGO_INITDB_ROOT_USERNAME=maurohcardona
    #   - MONGO_INITDB_ROOT_PASSWORD=estufa10
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
